learning_user/basicapp/urls.py
from django.conf.urls import url
from basicapp import views
from django.urls import path


app_name='basicapp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),

]

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls')),
    path('special/',views.special,name='special'),
    path('logout/',views.user_logout,name='logout'),
]

learning_user/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to="profile_pic",blank=True)


    def __str__(self):
        return self.user.username

learning_user/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learning_user/basicapp/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')

@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required()
def special(request):
    return HttpResponse("u r logged in , Nice !")



def register(request):
    registered=False

    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True

        else:
                print(user_form.errors,profile_form.errors)

    else:
            user_form=UserForm
            profile_form=UserProfileInfoForm()

    return render(request,'basicapp/register.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
    
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account Not Active.')
        else:
            print('sum1 tried to login & failed .')
            print('username:{} and password:{}'.format(username,password))
            return HttpResponse('invalid login supplied.')
    else:
        return render(request,'basicapp/login.html',{})
        

learning_user/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">

    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand"href="{% url 'index' %}">DJango</a> </li>
            <li><a class="navbar-link"href="{% url 'admin:index' %}">Admin</a> </li>
            <li><a class="navbar-link"href="{% url 'basicapp:register' %}">Register</a> </li>
            {% if user.is_authenticated %}
            <li><a class="navbar-link"href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a> </li>
            {% endif %}

        </ul>
    </div>



</nav>
    <div class="container">
        {% block body_block%}

        {% endblock %}
    </div>


</body>
</html>

learning_user/templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five </h1>

</div>


{% endblock %}

learning_user/templates/basicapp/login.html
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">

    <h1>Please Login </h1>
    <form action="{% url 'basicapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username"> Username: </label>
        <input type="text" name="username" placeholder="Enter Username ">

        <label for="password"> Password: </label>
        <input type="password" name="password">

        <input type="submit" value=" Login ">

    </form>


</div>
{% endblock %}

learning_user/templates/basicapp/register.html
{% extends "basicapp/base.html" %}
{% load staticfiles %}

{% block body_block%}

<div class="jumbotron">
    {% if registered %}
        <h1> Thank you for Registeration .</h1>
    {% else %}
        <h1> Register Here </h1>
        <h3> Fill out the form </h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{profile_form.as_p }}
            <input type="submit" value="Register">
            <h3>End line</h3>

        </form>
    {% endif %}

</div>

{% endblock %}